[project]
name = "http-mcp"
authors = [{ name = "Yeison Liscano", email = "yliscanoc@gmail.com" }]
maintainers = [{ name = "Yeison Liscano", email = "yliscanoc@gmail.com" }]
classifiers = [
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
keywords = ["mcp", "llm", "automation", "http"]
description = "This is a HTTP implementation of the MCP protocol"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.10"
version = "0.4.0"

dependencies = ["pydantic==2.12.3", "uvicorn==0.37.0", "starlette==0.48.0"]

[dependency-groups]
dev = [
    "httpx==0.28.1",
    "mdformat==1.0.0",
    "mypy==1.18.2",
    "pytest==8.4.2",
    "ruff==0.14.1",
    "pytest-cov==7.0.0",
    "pytest-asyncio==1.2.0",
]

[tool.hatch.build.targets.wheel]
packages = ["src/http_mcp"]

[project.urls]
Homepage = "https://github.com/yeison-liscano/http_mcp"
Issues = "https://github.com/yeison-liscano/http_mcp/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[tool.uv.sources]
microsoft-python-type-stubs = { git = "https://github.com/microsoft/python-type-stubs.git" }
