permissions: read-all
concurrency:
  cancel-in-progress: true
  group: ${{ github.actor }}

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@c2d88d3ecc89a9ef08eebf45d9637801dcee7eb5

      - name: "Set up Python"
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@06e4edb239928eb926db9fa84abd11632bf44baa

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        run: uv run pytest --cov=src --cov-fail-under=90 tests/

      - name: Run mypy
        run: uv run mypy . --config-file mypy.ini

      - name: Run ruff
        run: uv run ruff check .

      - name: Run mdformat
        run: uv run mdformat README.md --check --wrap 80

name: dev
on:
  pull_request:
    branches: [main]